{% set name = "modelparameters" %}
{% set version = "2024.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 09a63d346d2fb677596c2b70a4d1411e87c5fcd35d917f2188263064f5936c3c

build:
  number: 0
  noarch: python
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - mpmath
    - numpy
    - pint
    - setuptools

test:
  imports:
    - modelparameters

  requires:
    - pip
    - python {{ python_min }}

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/modelparameters
  summary: A module providing parameter structure for physical modeling
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - LICENSE_sympy
  doc_url: https://computationalphysiology.github.io/modelparameters/
  dev_url: https://github.com/ComputationalPhysiology/modelparameters

extra:
  recipe-maintainers:
    - finsberg
